### ISSUE TITLE
Hyperlink should be opened in new tab in preview mode

### ISSUE THREAD

**Issue by huyng12** [thien-do/samuwrite.com#122]
Add target=_blank to all hyperlink when render markdown.

**Comment by thien-do** [comment]
Not completely done but at least external links now have "_blank" when rendered in Preview

https://github.com/thien-do/samuwrite.com/commit/9df195c64911ae55ccbe84d7c21ac043156edd47

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/5953369/188282239-d0d9a5dd-2315-47f6-9835-81dd0a9c5039.png">
