### ISSUE TITLE
Lazy-load preview dependencies

### ISSUE THREAD

**Issue by huyng12** [thien-do/samuwrite.com#129]
Preview depends on unified and some plugins, but it is not required in the initial load.

Lazy-load its dependencies and cache for faster load time.

**Comment by huyng12** [comment]
https://v2.parceljs.org/features/code-splitting/

**Comment by thien-do** [comment]
Hm doesn't seem to worth the effort 🤔 

<img width="777" alt="image" src="https://user-images.githubusercontent.com/5953369/188310552-dd410fb1-2dfe-4131-a459-c733d373f118.png">

<img width="777" alt="image" src="https://user-images.githubusercontent.com/5953369/188310565-041e3b43-1a71-4ea6-bfe5-3011b248cc38.png">
