### ISSUE TITLE
Configurable escape key

### ISSUE THREAD

**Issue by ZeroX-DG** [thien-do/samuwrite.com#133]
Instead of using `esc` to exit insert mode. I wanted to use `jj` instead but it seems that we have no way to configure this currently.

**Comment by thien-do** [comment]
Hi @ZeroX-DG thanks for creating the issue! Custom key map for Vim mode is something we definitely want to do, but currently don't have enough funding to work on it yet.

That being said, for this specific use case, I'm happy to add them manually in the code: https://github.com/thien-do/samuwrite.com/commit/472999d2ac5859649a0a1f06f396fd04504531c3#diff-2b13776545d22af17a991efa9e04e42b3286f3b712276025f1924b9bffbc1cb9R17

Feel free to PR for any common key map you think would be useful for Samuwrite users!

Guides:
- https://github.com/codemirror/codemirror5/issues/2840#issuecomment-58125831
- https://github.com/brijeshb42/monaco-vim#adding-custom-key-bindings
- https://github.com/thien-do/samuwrite.com/commit/472999d2ac5859649a0a1f06f396fd04504531c3
