### ISSUE TITLE
Letter spacing break on select

### ISSUE THREAD

**Issue by monodyle** [thien-do/samuwrite.com#69]
Text letter getting closer on mouse select or double click to long text.

https://user-images.githubusercontent.com/30283022/133470305-e3394036-a614-4a57-913d-36f8857600bf.mp4

User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

Firefox's console:

![image](https://user-images.githubusercontent.com/30283022/133470272-d3dccd80-2d21-4346-b7f2-173a5d642351.png)

**Comment by thien-do** [comment]
https://user-images.githubusercontent.com/5953369/188282336-79392e89-d149-4ed8-9542-99474cfbea21.mov

Can you try again on samuwrite.com? I think we fixed it 🤞
